### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by KazuCocoa**

### CODE REVIEW

**Comment by KazuCocoa** [comment]
I haven't checked if Azure has proper macOS versions, but let me prepare the target.

**Comment by mykola-mokhnach** [comment]
Integration tests won't work on CI. One must enable XCode accessibility access manually once in order to make it possible

**Comment by KazuCocoa** [comment]
Oh, gotcha. It's reasonable for security, but sad for us

**Comment by mykola-mokhnach** [comment]
@KazuCocoa It still makes sense to have Azure enabled to run unit tests and linting

**Comment by KazuCocoa** [comment]
sounds good

**Pull request closed without merging**
